name: pro_profile
description: "Signify a professional profile, indicating a platform or service where freelancers 
can create and showcase their professional profiles."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_neumorphic_plus: ^3.3.0
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  elastic_drawer: ^2.0.2
  google_fonts: ^6.2.1
  easy_stepper: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/